language: node_js
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: IcGbW3fpSwhiPvlLRGxLyvbDb9uYn+K9sJPqkHpZVxezCq0Oqf/YSt8tm4wzBIZFeETMhT+ijJ6ghaQXYcyRXIZJS6QvE8WE6K3yl97t78IPLc2Ld3E25lHhlZUsjCWeK/nRkqyOLRIveMkytGZ6wM91a6dEn5PiNnQEGDo67RpIJAIBnSDb9tZuBQqx+vPK+bQsKwGTPrAxNeCWg54hjn/b6CvRvZ6GZrQXjPRalXRszWDcjwp/0nnnM6qc1NmzrSMJSgaWceMuvHepN7glKDBJszWjfJdmOZKQy28D1H1v+ad5vu+3nCyJ10B+rYKianid0cEIwnGs+bPUnBnobIX7YU7d5XiPPmo0AYovkS9I8WGrQIhfXRv/8ecysHYYxbICWAJ/py7nUtx5ZcHx01HVMH5tixlYiCtErVz/vyGxZPvGmqDu0wmCbQsV8woDCHyG3MmrpCfo162top/C/iF2QlVd4C447M2o3VbReamKyy7O4em40yU86FmcMrYbMdDaGRRfZj69W3DACuil4GY1VgPS4DcYe5LkHfWoKVbFR2lmJ8hzX7HTCRCAwvELlUoZeWeRp9VxYPS+tl3BjX1ESvGnreEQzQfaBRmmihWS7CNF1Cw5hAu9kttHRTbPxJHqEe0oKlKgM93HDELJc+Ah72/pbO+JF47pAvJiR80=
  app: damp-lake-24293
  on:
    repo: froydroyce/quantified_self
