language: node_js
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: lPUvpG+31x+DkEUcZbdvOOtwULtBuUMug4AXnHQqUSEW8nzBru7mhrd01Z92IynCxTHrahHWNI/YNMKn6gfM2PRhE9rCBeEjmKSkhbrNbPgtQ6OjM24sdoQumcyFIfYOidgsT7C/qyklCZPkWHzxoIOHuYUJOK3qc8Z6sudRrH6TJxhG7dAHW5DUxP9niyOyAwjKYbIBsrdDgTVonsZC7MlgBGXAVVvpDV+yIF5bs4s9tUO2nJJJQuq1QoLMwWLNUxTV8PqVDSRpNqbSZncj670rS5WP7pmT8z10euiPI0F5Ic2KhrzB1u8EiNJyFjp83mS1ZwyVxwYHN1DtAkVA9lB0DkhKi/aVpEHmBUIJFtrH+9aHxpRnZnCDNvnGQc0+oq1VcaXwgObuKbo9gU4WEfJ2kPQVnEihZc9z7AxtwOlfY81+EfhRwHIlVZlXub8/NZGVTgxF06bhZXed2m9h2U99j4GN4Nrth0E31qbXtKV8o7EpDjA9BjPAtB70TL43Z7jyjHDDn5VYNG7b2qzrKI50108BXHIPXwUUDauttpAM6ojh+MUSer2dDN0gnKqCeD7Pn1uX00GYlOt1pB5JSbF4POMT24OPCwDlQcESa1+mHFXPGyhdJcbdIA7l/e1RfH3ePuAYoxPtvpRhfAe5qjoWlsIrisAW6+gI2PZwhKs=
  app: damp-lake-24293
  on:
    repo: froydroyce/quantified_self
