language: node_js
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: FRKAyxI8lRXF7UvJ1jAjundCzhEEqFx6oyOitZ1ohU9t/FSBmUpiin7cqU38CTJnWCvw1USoAqlEHTMz/7zNQPmZe+OvCaAsCaAfxPU83kDH/THGrRcEI9xofIoQfAAQ/m4tnFR/dnlCbh+jDyPJ+RpXBW3eeYcPEiLb3kZUqo/r1XMXPf+30ksB2lic6NT1PGK2tUyb2ZbPfXGqJ+Iv4HZ2XcYiKDGEu6HsIGyc8u1fJUU6PcukkYeBtBntZ1qSgyqn8Hr8Y7beLUqhRQbRXl10UGYKrSbzqEwTP2k8Ctg1fTHi4b9cXtxAL4PPgSSQFkfjmRxualsygL9Mq+R1E/fVopgG9oymQAD6chp7UHFFU5Z45o2hvmdTniFyAHX8qE31l3t9WZHuQBhMQKA4+iRnVEWlgvkJavC3NTRml2qYFKC8wtF4aJn+EzcnHuO9A/ZhYbnXEis7ki7yaO3glkWjAVOv+gonYx6uYXDEZOj7sV+lFoaQVY3SuNPN6WOs247SlcwoQLHywp278es998b21G/Va8BkhLh+CM1T0u+5VQNn6Nr7QD3nTzOhIwXsET/JF9YgPEapR572AH8gRbjZB4riepU/u0Uc/vbWgVft3usVhm1Jv+hrYSpx1zLmXAKkGRrWwttXYFUVXvDsYBHvJORophd8G5YHIygxw/Q=
  app: damp-lake-24293
  on:
    repo: froydroyce/quantified_self
