language: node_js
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: b27qacqEHUgndzwgk8EYeqVsKly51NAzQSR/S6qzIlG5NqxvM4mAy/UMBsRAaSaoepBo6tM676rCYTMfm56bMRn533ngxjAmWZp6E/+Uq2QviH6Wjo6fH3idevnN+0AJfubOBOreqeIUuF3UVhIZhFI0nhNuZkRSzAxJzN4DXJ3JkBMwrAMOUotqHBK7CtpFVSufX7dygz5cgfucgpPv/s57IiIS65KLLx+EVicoEqZE0RzsJNYj6D9W2oa+5mvUY+HXrQKQS/t60gnQHameQK8BG4XFjs0ay4ZfuxxfVaYOUM6VH7+4OwJCh3r2fAV0hKQZKQhLStLzL06XukKi9S0XRdZP8bfB+74mQVEDcdamiKLmkEzMhZY4TEtGG764D6oxIrEAGLkG5m9sGcLTCmgpuhOWDHIQbZXgeVHIqqdRaa0lBfJDoJIkW39bD3lkjAXDy1NCE2wMTPyVvtJGe7R52z8fWBvkc402kMfzuEAghl6hvMHMP+n2d99Awy+iGNVL0vT9CjIjbC9+lba6yOLFeARPYC2Q3Nz2qTbaFeO4kXSRHuq8hOLvBDSCQMmzYS3pOAWwfVcRUYU8reI3gGmKPA/oa0TOG6WxGz2AQxrNGeXC1i/aKcWN0XtzoRax1WUfUEZ6WTuDy6hdVYT9G6cRedwdQbm2TlvK4up5gKI=
  app: damp-lake-24293
  on:
    repo: froydroyce/quantified_self
