language: node_js
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: ZucdF7AKlnN4coAbhps8KsP+AjYo1HzoUX08t9YZQ5OdMBIUhDaF2529WuyNK4LKxa2i0V6mEdH3ZEhQsC0lIL7yibuvlrCysD/+wCY3ElgvSY5ncqIP2/X2kjW+DUAJ7AWb5sHJL3Xw6M4EQTmF04ckkKrhzmjyz3owbqkui1ui46K0Wqu+XEx0JIm7NEh5SL03T0+zfe6GqYyEtBn2/FnM14P7O+++HGEkJFOrMD+LoeBT5M0FLGDIU4zWk0eWdsgIvwassQB5OoNu2uKs0PoK/S6pDC/fXElWXK/H9miC3xPHxPlqhqN3J7m1GcfpUiRlqDY8nqqjDK9JjvCf6BM0PKVPtVx+mivZYW2kkit2dgqcdAT3sPdO/ZsGRlW2zwqlBDIoPTHwRmSncnQT9aBgRBEXxVqtBB8NGswuILL/9S0OQA9RRrcHO37bsHooQhh3OWbEgRPbX2bl8xK2OvwwlERZ+8ab3HNpyVQKs4Eivh3T3O3hVfV5c+r4kaK0yO+Hq8TzagdG3CojqHtFXfhEZ/nCuvuqgBthKsa/msblBarldWHwaRckASIm1B6CQM1UtLQddsi/5ooAtEpBHjHv/E1Kq9IEVmLNV6MQwZ9tKGNWcpzPQ8LuHMwDvQznmyzPP+XjmuKbIkK+DyWzMRClPxeDl+Cys51flWruXv4=
